# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 728)
        self.main_window_grid = QtWidgets.QGridLayout(MainWindow)
        self.main_window_grid.setContentsMargins(0, 0, 0, 0)
        self.main_window_grid.setSpacing(0)
        self.main_window_grid.setObjectName("main_window_grid")
        self.CustomWindow = QtWidgets.QFrame(MainWindow)
        self.CustomWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CustomWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CustomWindow.setObjectName("CustomWindow")
        self.custom_window_grid = QtWidgets.QGridLayout(self.CustomWindow)
        self.custom_window_grid.setContentsMargins(0, 0, 0, 0)
        self.custom_window_grid.setSpacing(0)
        self.custom_window_grid.setObjectName("custom_window_grid")
        self.custom_window_grid_2 = QtWidgets.QGridLayout()
        self.custom_window_grid_2.setSpacing(0)
        self.custom_window_grid_2.setObjectName("custom_window_grid_2")
        self.grip_frame = QtWidgets.QFrame(self.CustomWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grip_frame.sizePolicy().hasHeightForWidth())
        self.grip_frame.setSizePolicy(sizePolicy)
        self.grip_frame.setMinimumSize(QtCore.QSize(20, 20))
        self.grip_frame.setMaximumSize(QtCore.QSize(20, 20))
        self.grip_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grip_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grip_frame.setObjectName("grip_frame")
        self.custom_window_grid_2.addWidget(self.grip_frame, 2, 1, 1, 1)
        self.empty_frame = QtWidgets.QFrame(self.CustomWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.empty_frame.sizePolicy().hasHeightForWidth())
        self.empty_frame.setSizePolicy(sizePolicy)
        self.empty_frame.setMinimumSize(QtCore.QSize(0, 20))
        self.empty_frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.empty_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.empty_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.empty_frame.setObjectName("empty_frame")
        self.custom_window_grid_2.addWidget(self.empty_frame, 2, 0, 1, 1)
        self.title_bar = QtWidgets.QFrame(self.CustomWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_bar.sizePolicy().hasHeightForWidth())
        self.title_bar.setSizePolicy(sizePolicy)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 50))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.title_bar_hbox = QtWidgets.QHBoxLayout(self.title_bar)
        self.title_bar_hbox.setContentsMargins(10, 10, 10, 10)
        self.title_bar_hbox.setSpacing(0)
        self.title_bar_hbox.setObjectName("title_bar_hbox")
        self.window_btns = QtWidgets.QWidget(self.title_bar)
        self.window_btns.setObjectName("window_btns")
        self.window_btns_hbox = QtWidgets.QHBoxLayout(self.window_btns)
        self.window_btns_hbox.setContentsMargins(0, 0, 0, 0)
        self.window_btns_hbox.setSpacing(16)
        self.window_btns_hbox.setObjectName("window_btns_hbox")
        self.close_btn = QtWidgets.QPushButton(self.window_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.close_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setStyleSheet("border-radius: 10px;\n"
"background-color: #ee6a5e;\n"
"color: rgb(141, 25, 17);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setIconSize(QtCore.QSize(0, 0))
        self.close_btn.setObjectName("close_btn")
        self.window_btns_hbox.addWidget(self.close_btn)
        self.minimize_btn = QtWidgets.QPushButton(self.window_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimize_btn.sizePolicy().hasHeightForWidth())
        self.minimize_btn.setSizePolicy(sizePolicy)
        self.minimize_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.minimize_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.minimize_btn.setStyleSheet("border-radius: 10px;\n"
"background-color: #f6be4f;")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/minimize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(0, 0))
        self.minimize_btn.setObjectName("minimize_btn")
        self.window_btns_hbox.addWidget(self.minimize_btn)
        self.maximize_btn = QtWidgets.QPushButton(self.window_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximize_btn.sizePolicy().hasHeightForWidth())
        self.maximize_btn.setSizePolicy(sizePolicy)
        self.maximize_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.maximize_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.maximize_btn.setStyleSheet("border-radius: 10px;\n"
"background-color: #62c554;")
        self.maximize_btn.setText("")
        self.maximize_btn.setIconSize(QtCore.QSize(0, 0))
        self.maximize_btn.setObjectName("maximize_btn")
        self.window_btns_hbox.addWidget(self.maximize_btn)
        self.title_bar_hbox.addWidget(self.window_btns)
        self.title = QtWidgets.QLabel(self.title_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.title_bar_hbox.addWidget(self.title)
        self.custom_window_grid_2.addWidget(self.title_bar, 0, 0, 1, 2)
        self.content_widget = QtWidgets.QFrame(self.CustomWindow)
        self.content_widget.setStyleSheet("")
        self.content_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_widget.setObjectName("content_widget")
        self.content_grid = QtWidgets.QGridLayout(self.content_widget)
        self.content_grid.setContentsMargins(0, 0, 0, 0)
        self.content_grid.setSpacing(0)
        self.content_grid.setObjectName("content_grid")
        self.stacked_widget = QtWidgets.QStackedWidget(self.content_widget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.login_widget = QtWidgets.QWidget()
        self.login_widget.setObjectName("login_widget")
        self.login_layout = QtWidgets.QGridLayout(self.login_widget)
        self.login_layout.setContentsMargins(0, 0, 0, 0)
        self.login_layout.setSpacing(0)
        self.login_layout.setObjectName("login_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.login_layout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.login_layout.addItem(spacerItem1, 1, 0, 1, 1)
        self.login_grid = QtWidgets.QGridLayout()
        self.login_grid.setSpacing(12)
        self.login_grid.setObjectName("login_grid")
        self.to_register_page_link = QtWidgets.QCommandLinkButton(self.login_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.to_register_page_link.setFont(font)
        self.to_register_page_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("none")
        self.to_register_page_link.setIcon(icon)
        self.to_register_page_link.setIconSize(QtCore.QSize(0, 0))
        self.to_register_page_link.setObjectName("to_register_page_link")
        self.login_grid.addWidget(self.to_register_page_link, 5, 0, 1, 1)
        self.password_edit = QtWidgets.QLineEdit(self.login_widget)
        self.password_edit.setInputMask("")
        self.password_edit.setMaxLength(100)
        self.password_edit.setFrame(True)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.login_grid.addWidget(self.password_edit, 3, 0, 1, 1)
        self.email_edit = QtWidgets.QLineEdit(self.login_widget)
        self.email_edit.setMaxLength(100)
        self.email_edit.setObjectName("email_edit")
        self.login_grid.addWidget(self.email_edit, 1, 0, 1, 1)
        self.email_label = QtWidgets.QLabel(self.login_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.login_grid.addWidget(self.email_label, 0, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.login_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.login_grid.addWidget(self.password_label, 2, 0, 1, 1)
        self.forgot_password_link = QtWidgets.QCommandLinkButton(self.login_widget)
        self.forgot_password_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("none")
        self.forgot_password_link.setIcon(icon)
        self.forgot_password_link.setIconSize(QtCore.QSize(0, 0))
        self.forgot_password_link.setObjectName("forgot_password_link")
        self.login_grid.addWidget(self.forgot_password_link, 6, 0, 1, 1)
        self.frame_for_login_btn = QtWidgets.QFrame(self.login_widget)
        self.frame_for_login_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_for_login_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_for_login_btn.setObjectName("frame_for_login_btn")
        self.login_grid.addWidget(self.frame_for_login_btn, 4, 0, 1, 1)
        self.login_layout.addLayout(self.login_grid, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.login_layout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.login_layout.addItem(spacerItem3, 2, 1, 1, 1)
        self.stacked_widget.addWidget(self.login_widget)
        self.register_widget = QtWidgets.QWidget()
        self.register_widget.setObjectName("register_widget")
        self.register_layout = QtWidgets.QGridLayout(self.register_widget)
        self.register_layout.setContentsMargins(0, 0, 0, 0)
        self.register_layout.setSpacing(0)
        self.register_layout.setObjectName("register_layout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.register_layout.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.register_layout.addItem(spacerItem5, 0, 1, 1, 1)
        self.register_grid = QtWidgets.QGridLayout()
        self.register_grid.setContentsMargins(30, 0, 30, 0)
        self.register_grid.setSpacing(12)
        self.register_grid.setObjectName("register_grid")
        self.register_password_edit = QtWidgets.QLineEdit(self.register_widget)
        self.register_password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_password_edit.setObjectName("register_password_edit")
        self.register_grid.addWidget(self.register_password_edit, 9, 0, 1, 1)
        self.passwords_match_validator = QtWidgets.QCheckBox(self.register_widget)
        self.passwords_match_validator.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passwords_match_validator.setFont(font)
        self.passwords_match_validator.setCheckable(True)
        self.passwords_match_validator.setObjectName("passwords_match_validator")
        self.register_grid.addWidget(self.passwords_match_validator, 14, 0, 1, 1)
        self.digits_letters_validator = QtWidgets.QCheckBox(self.register_widget)
        self.digits_letters_validator.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.digits_letters_validator.setFont(font)
        self.digits_letters_validator.setCheckable(True)
        self.digits_letters_validator.setObjectName("digits_letters_validator")
        self.register_grid.addWidget(self.digits_letters_validator, 13, 0, 1, 1)
        self.repeat_password_edit = QtWidgets.QLineEdit(self.register_widget)
        self.repeat_password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeat_password_edit.setObjectName("repeat_password_edit")
        self.register_grid.addWidget(self.repeat_password_edit, 11, 0, 1, 1)
        self.register_email_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_email_label.setFont(font)
        self.register_email_label.setObjectName("register_email_label")
        self.register_grid.addWidget(self.register_email_label, 1, 0, 1, 1)
        self.to_login_page_arrow = QtWidgets.QCommandLinkButton(self.register_widget)
        self.to_login_page_arrow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_login_page_arrow.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/left-arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_login_page_arrow.setIcon(icon2)
        self.to_login_page_arrow.setIconSize(QtCore.QSize(25, 25))
        self.to_login_page_arrow.setObjectName("to_login_page_arrow")
        self.register_grid.addWidget(self.to_login_page_arrow, 0, 0, 1, 1)
        self.register_email_edit = QtWidgets.QLineEdit(self.register_widget)
        self.register_email_edit.setObjectName("register_email_edit")
        self.register_grid.addWidget(self.register_email_edit, 2, 0, 1, 1)
        self.register_email_error_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.register_email_error_label.setFont(font)
        self.register_email_error_label.setText("")
        self.register_email_error_label.setWordWrap(True)
        self.register_email_error_label.setObjectName("register_email_error_label")
        self.register_grid.addWidget(self.register_email_error_label, 3, 0, 1, 1)
        self.register_nick_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_nick_label.setFont(font)
        self.register_nick_label.setObjectName("register_nick_label")
        self.register_grid.addWidget(self.register_nick_label, 4, 0, 1, 1)
        self.valid_symbols_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.valid_symbols_label.setFont(font)
        self.valid_symbols_label.setObjectName("valid_symbols_label")
        self.register_grid.addWidget(self.valid_symbols_label, 6, 0, 1, 1)
        self.repeat_password_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repeat_password_label.setFont(font)
        self.repeat_password_label.setObjectName("repeat_password_label")
        self.register_grid.addWidget(self.repeat_password_label, 10, 0, 1, 1)
        self.length_validator = QtWidgets.QCheckBox(self.register_widget)
        self.length_validator.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.length_validator.setFont(font)
        self.length_validator.setCheckable(True)
        self.length_validator.setChecked(False)
        self.length_validator.setObjectName("length_validator")
        self.register_grid.addWidget(self.length_validator, 12, 0, 1, 1)
        self.register_nick_edit = QtWidgets.QLineEdit(self.register_widget)
        self.register_nick_edit.setObjectName("register_nick_edit")
        self.register_grid.addWidget(self.register_nick_edit, 5, 0, 1, 1)
        self.register_password_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_password_label.setFont(font)
        self.register_password_label.setObjectName("register_password_label")
        self.register_grid.addWidget(self.register_password_label, 8, 0, 1, 1)
        self.register_nick_error_label = QtWidgets.QLabel(self.register_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.register_nick_error_label.setFont(font)
        self.register_nick_error_label.setText("")
        self.register_nick_error_label.setObjectName("register_nick_error_label")
        self.register_grid.addWidget(self.register_nick_error_label, 7, 0, 1, 1)
        self.register_layout.addLayout(self.register_grid, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.register_layout.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.register_layout.addItem(spacerItem7, 1, 0, 1, 1)
        self.stacked_widget.addWidget(self.register_widget)
        self.main_widget = QtWidgets.QWidget()
        self.main_widget.setObjectName("main_widget")
        self.main_widget_main_hbox = QtWidgets.QHBoxLayout(self.main_widget)
        self.main_widget_main_hbox.setContentsMargins(0, 0, 0, 0)
        self.main_widget_main_hbox.setSpacing(0)
        self.main_widget_main_hbox.setObjectName("main_widget_main_hbox")
        self.main_widget_main_splitter = QtWidgets.QSplitter(self.main_widget)
        self.main_widget_main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_widget_main_splitter.setHandleWidth(2)
        self.main_widget_main_splitter.setChildrenCollapsible(False)
        self.main_widget_main_splitter.setObjectName("main_widget_main_splitter")
        self.main_widget_left_widget = QtWidgets.QWidget(self.main_widget_main_splitter)
        self.main_widget_left_widget.setObjectName("main_widget_left_widget")
        self.main_widget_left_widget_grid = QtWidgets.QGridLayout(self.main_widget_left_widget)
        self.main_widget_left_widget_grid.setContentsMargins(0, 10, 0, 0)
        self.main_widget_left_widget_grid.setSpacing(0)
        self.main_widget_left_widget_grid.setObjectName("main_widget_left_widget_grid")
        self.main_widget_left_widget_grid_2 = QtWidgets.QGridLayout()
        self.main_widget_left_widget_grid_2.setHorizontalSpacing(20)
        self.main_widget_left_widget_grid_2.setVerticalSpacing(10)
        self.main_widget_left_widget_grid_2.setObjectName("main_widget_left_widget_grid_2")
        self.to_menu_page_btn = QtWidgets.QPushButton(self.main_widget_left_widget)
        self.to_menu_page_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.to_menu_page_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.to_menu_page_btn.setIcon(icon3)
        self.to_menu_page_btn.setObjectName("to_menu_page_btn")
        self.main_widget_left_widget_grid_2.addWidget(self.to_menu_page_btn, 0, 0, 1, 1)
        self.search = QtWidgets.QLineEdit(self.main_widget_left_widget)
        self.search.setObjectName("search")
        self.main_widget_left_widget_grid_2.addWidget(self.search, 0, 1, 1, 1)
        self.users_list = QtWidgets.QListWidget(self.main_widget_left_widget)
        self.users_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.users_list.setObjectName("users_list")
        item = QtWidgets.QListWidgetItem()
        self.users_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.users_list.addItem(item)
        self.main_widget_left_widget_grid_2.addWidget(self.users_list, 1, 0, 1, 2)
        self.main_widget_left_widget_grid.addLayout(self.main_widget_left_widget_grid_2, 0, 0, 1, 1)
        self.main_widget_right_widget = QtWidgets.QWidget(self.main_widget_main_splitter)
        self.main_widget_right_widget.setObjectName("main_widget_right_widget")
        self.main_widget_right_widget_grid = QtWidgets.QGridLayout(self.main_widget_right_widget)
        self.main_widget_right_widget_grid.setContentsMargins(0, 0, 0, 0)
        self.main_widget_right_widget_grid.setSpacing(0)
        self.main_widget_right_widget_grid.setObjectName("main_widget_right_widget_grid")
        self.main_widget_right_widget_grid_2 = QtWidgets.QGridLayout()
        self.main_widget_right_widget_grid_2.setSpacing(0)
        self.main_widget_right_widget_grid_2.setObjectName("main_widget_right_widget_grid_2")
        self.user_info_widget = QtWidgets.QWidget(self.main_widget_right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_info_widget.sizePolicy().hasHeightForWidth())
        self.user_info_widget.setSizePolicy(sizePolicy)
        self.user_info_widget.setMinimumSize(QtCore.QSize(0, 70))
        self.user_info_widget.setObjectName("user_info_widget")
        self.main_widget_right_widget_grid_2.addWidget(self.user_info_widget, 0, 0, 1, 1)
        self.dialog_window_and_message_edit_widget = QtWidgets.QWidget(self.main_widget_right_widget)
        self.dialog_window_and_message_edit_widget.setObjectName("dialog_window_and_message_edit_widget")
        self.dialog_window_and_message_edit_widget_grid = QtWidgets.QVBoxLayout(self.dialog_window_and_message_edit_widget)
        self.dialog_window_and_message_edit_widget_grid.setContentsMargins(0, 0, 0, 0)
        self.dialog_window_and_message_edit_widget_grid.setSpacing(0)
        self.dialog_window_and_message_edit_widget_grid.setObjectName("dialog_window_and_message_edit_widget_grid")
        self.dialog_window_and_message_edit_splitter = QtWidgets.QSplitter(self.dialog_window_and_message_edit_widget)
        self.dialog_window_and_message_edit_splitter.setOrientation(QtCore.Qt.Vertical)
        self.dialog_window_and_message_edit_splitter.setHandleWidth(2)
        self.dialog_window_and_message_edit_splitter.setChildrenCollapsible(False)
        self.dialog_window_and_message_edit_splitter.setObjectName("dialog_window_and_message_edit_splitter")
        self.dialog_window = QtWidgets.QListWidget(self.dialog_window_and_message_edit_splitter)
        self.dialog_window.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dialog_window.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dialog_window.setWordWrap(True)
        self.dialog_window.setObjectName("dialog_window")
        item = QtWidgets.QListWidgetItem()
        self.dialog_window.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dialog_window.addItem(item)
        self.message_edit = QtWidgets.QPlainTextEdit(self.dialog_window_and_message_edit_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_edit.sizePolicy().hasHeightForWidth())
        self.message_edit.setSizePolicy(sizePolicy)
        self.message_edit.setMinimumSize(QtCore.QSize(0, 50))
        self.message_edit.setObjectName("message_edit")
        self.dialog_window_and_message_edit_widget_grid.addWidget(self.dialog_window_and_message_edit_splitter)
        self.main_widget_right_widget_grid_2.addWidget(self.dialog_window_and_message_edit_widget, 1, 0, 1, 1)
        self.main_widget_right_widget_grid.addLayout(self.main_widget_right_widget_grid_2, 0, 0, 1, 1)
        self.main_widget_main_hbox.addWidget(self.main_widget_main_splitter)
        self.stacked_widget.addWidget(self.main_widget)
        self.content_grid.addWidget(self.stacked_widget, 0, 0, 1, 1)
        self.custom_window_grid_2.addWidget(self.content_widget, 1, 0, 1, 2)
        self.custom_window_grid.addLayout(self.custom_window_grid_2, 0, 0, 1, 1)
        self.main_window_grid.addWidget(self.CustomWindow, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Minigram"))
        self.title.setText(_translate("MainWindow", "Minigram"))
        self.to_register_page_link.setText(_translate("MainWindow", "Регистрация"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.password_label.setText(_translate("MainWindow", "Пароль"))
        self.forgot_password_link.setText(_translate("MainWindow", "Забыл пароль?"))
        self.passwords_match_validator.setText(_translate("MainWindow", "Пароли совпадают"))
        self.digits_letters_validator.setText(_translate("MainWindow", "Пароль содержит как буквы, так и цифры"))
        self.register_email_label.setText(_translate("MainWindow", "Email"))
        self.register_nick_label.setText(_translate("MainWindow", "Придумайте ник"))
        self.valid_symbols_label.setText(_translate("MainWindow", "Допускаются латиница, цифры и нижнее подчёркивание"))
        self.repeat_password_label.setText(_translate("MainWindow", "Повторите пароль"))
        self.length_validator.setText(_translate("MainWindow", "Длина пароля больше 8 символов"))
        self.register_password_label.setText(_translate("MainWindow", "Пароль"))
        self.search.setPlaceholderText(_translate("MainWindow", "Поиск"))
        __sortingEnabled = self.users_list.isSortingEnabled()
        self.users_list.setSortingEnabled(False)
        item = self.users_list.item(0)
        item.setText(_translate("MainWindow", "test user 1"))
        item = self.users_list.item(1)
        item.setText(_translate("MainWindow", "test user 2"))
        self.users_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.dialog_window.isSortingEnabled()
        self.dialog_window.setSortingEnabled(False)
        item = self.dialog_window.item(0)
        item.setText(_translate("MainWindow", "test message 1"))
        item = self.dialog_window.item(1)
        item.setText(_translate("MainWindow", "test message 2"))
        self.dialog_window.setSortingEnabled(__sortingEnabled)
        self.message_edit.setPlaceholderText(_translate("MainWindow", "Написать сообщение..."))
